spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/yun?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
