CREATE DATABASE yun;
USE yun;

CREATE TABLE `helloDO`(
`keyword` VARCHAR(20) NOT NULL
);

CREATE TABLE `user`(
`id` INT PRIMARY KEY AUTO_INCREMENT COMMENT '用户id',
`username` VARCHAR(20) NOT NULL COMMENT '用户名',
`email` VARCHAR(20) NOT NULL COMMENT '邮箱',
`pwd` VARCHAR(20) NOT NULL COMMENT '密码',
`registerTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
`lastLoginTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上次登录时间',
`loginIp` VARCHAR(20) NOT NULL COMMENT '登录IP',
`status` INT NOT NULL COMMENT '账号状态'
)COMMENT '用户表';